<?php
/**
 * @file
 * Client/server communication for the Echoes module.
 */

/**
 * Implements hook_menu().
 */
function echoes_menu() {
  $items['echoes/push'] = array(
    'page callback' => 'echoes_push',
    'access arguments' => array('send and receive echoes'),
    'type' => MENU_CALLBACK,
  );

  $items['echoes/get'] = array(
    'page callback' => 'echoes_get',
    'access arguments' => array('send and receive echoes'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function echoes_permission() {
  return array(
    'send and receive echoes' =>  array(
      'title' => t('Send and receive echoes'),
      'description' => t('Allow users to participate with echoes functionality on the front end.'),
    ),
  );
}

/**
*
*/
function echoes_push () {
  $euid = !empty($_GET['euid']) ? $_GET['euid'] : NULL;
  $path = !empty($_GET['path']) ? $_GET['path'] : NULL;
  $selector = !empty($_GET['selector']) ? $_GET['selector'] : NULL;
  $created = !empty($_GET['created']) ? $_GET['created'] : NULL;

  if (!$euid || !$path || !$selector || !$created) {
    drupal_json_output(array('success' => false));
    exit;
  }

  $echoes_data = variable_get('echoes_data', array());

  $echoes_data[] = array(
    'euid' => $euid,
    'path' => $path,
    'selector' => $selector,
    'created' => $created,
  );
  variable_set('echoes_data', $echoes_data);
  drupal_json_output(array('success' => true));
}

/**
*
*/
function echoes_get () {
  $echoes_data = variable_get('echoes_data', array());
  drupal_json_output(array('data' => $echoes_data));
}
